export const MenuApi = [
    {
        id: 1,
        name: "Food1",
        category: "Breakfast",
        price: 100,
        image: "images/food_1.png",
        description: "Food1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 2,
        name: "Food2",
        category: "Breakfast",
        price: 120,
        image: "images/food_2.png",
        description: "Food2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 3,
        name: "Food3",
        category: "Breakfast",
        price: 220,
        image: "images/food_4.png",
        description: "Food3 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 4,
        name: "Food4",
        category: "Lunch",
        price: 1120,
        image: "images/food_5.png",
        description: "Food4 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 5,
        name: "Food5",
        category: "Lunch",
        price: 20,
        image: "images/food_6.png",
        description: "Food5 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 6,
        name: "Food6",
        category: "Dinner",
        price: 70,
        image: "images/food_7.png",
        description: "Food6 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 7,
        name: "Food7",
        category: "Dinner",
        price: 180,
        image: "images/food_8.png",
        description: "Food7 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 8,
        name: "Food8",
        category: "Lunch",
        price: 1020,
        image: "images/food_9.png",
        description: "Food8 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 9,
        name: "Food9",
        category: "Breakfast",
        price: 720,
        image: "images/food_10.png",
        description: "Food9 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 10,
        name: "Food10",
        category: "Lunch",
        price: 420,
        image: "images/food_11.png",
        description: "Food-10 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 11,
        name: "Food11",
        category: "Dinner",
        price: 220,
        image: "images/food_12.png",
        description: "Food Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 12,
        name: "Food12",
        category: "Snacks",
        price: 520,
        image: "images/food_13.png",
        description: "Food Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 13,
        name: "Food13",
        category: "Snacks",
        price: 150,
        image: "images/food_14.png",
        description: "Food Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 14,
        name: "Food14",
        category: "Snacks",
        price: 190,
        image: "images/food_15.png",
        description: "Food-14 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 15,
        name: "Food15",
        category: "Snacks",
        price: 170,
        image: "images/food_16.png",
        description: "Food-15 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 16,
        name: "Food16",
        category: "Breakfast",
        price: 1560,
        image: "images/food_17.png",
        description: "Food-16 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 17,
        name: "Food17",
        category: "Lunch",
        price: 550,
        image: "images/food_18.png",
        description: "Food-17 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 18,
        name: "Food18",
        category: "Breakfast",
        price: 199,
        image: "images/food_19.png",
        description: "Food-18 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 19,
        name: "Food19",
        category: "Dinner",
        price: 99,
        image: "images/food_20.png",
        description: "Food-19 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 20,
        name: "Food20",
        category: "Dinner",
        price: 236,
        image: "images/food_21.png",
        description: "Food-20 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 21,
        name: "Food21",
        category: "Snacks",
        price: 456,
        image: "images/food_22.png",
        description: "Food-21 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 22,
        name: "Food22",
        category: "Snacks",
        price: 55,
        image: "images/food_23.png",
        description: "Food-22 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 23,
        name: "Food23",
        category: "Snacks",
        price: 120,
        image: "images/food_24.png",
        description: "Food-23 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 24,
        name: "Food24",
        category: "Snacks",
        price: 120,
        image: "images/food_25.png",
        description: "Food-24 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 25,
        name: "Food25",
        category: "Snacks",
        price: 120,
        image: "images/food_8.png",
        description: "Food-24 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
    {
        id: 26,
        name: "Food26",
        category: "Lunch",
        price: 240,
        image: "images/food_25.png",
        description: "Food-24 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod possimus quis asperiores nesciunt, harum corrupti itaque ea blanditiis temporibus q",
    },
];